"""initial version of JH daily reports

Revision ID: 8497fb70170b
Revises:
Create Date: 2020-04-17 13:10:32.110282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8497fb70170b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jh_daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_region', sa.String(), nullable=True),
    sa.Column('province_state', sa.String(), nullable=True),
    sa.Column('fips', sa.String(), nullable=True),
    sa.Column('admin2', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jh_daily_reports_id'), 'jh_daily_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jh_daily_reports_id'), table_name='jh_daily_reports')
    op.drop_table('jh_daily_reports')
    # ### end Alembic commands ###
